name: "Lint workflows"

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint-workflows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rhysd/actionlint@v1
        with:
          fail-level: error
