name: "Release Dev Container Templates"
on:
  push:
    tags:
      - '*-v*'

jobs:
  deploy:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: "Publish Templates"
        uses: devcontainers/action@v1
        with:
          publish-templates: "true"
          base-path-to-templates: "./src"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
